[package]
name = "gcmap"
version = "0.1.4"
authors = ["Arvid E. Picciani <aep@exys.org>"]
license = "MIT"
description = "HashMap which removes entries when an external marker is dropped"
repository = "https://github.com/aep/gcmap"

[dependencies]
